authors:
  vinny:
    name: Vincent Lelandais
    description: CS lead
    avatar: https://github.com/squidfunk.png
  calebmidgley:
    name: Caleb Midgley
    description: Product manager
    avatar: https://github.com/alexvoss.png